### ISSUE TITLE
[🐛 버그] Account 로그인 api 500 에러

### ISSUE THREAD

**Issue by youngrongoh** [LM-channel-team-project/WantoDo#130]
## 🐛 Bug report

![500 에러메시지](https://user-images.githubusercontent.com/64844815/116901178-91f70180-ac74-11eb-8dc4-ad159adf56b9.png)
![서버 에러 메시지](https://user-images.githubusercontent.com/64844815/116902181-cb7c3c80-ac75-11eb-83d4-591ef1645977.png)

## 예상된 기능 혹은 화면
사용자 profile 객체 반환

## 재연할 수 있는 방법

![id token](https://user-images.githubusercontent.com/64844815/116901360-cb2f7180-ac74-11eb-86e3-0bc8cc057daf.png)

구글로 부터 받은 id_token 값을 헤더에 담아 post 요청을 보내면 500 에러 표시됨

**Comment by castleMo** [comment]
혹시 front GOOGLE_CLIENT_ID랑 back GOOGLE_CLIENT_ID 같은지 알 수 있을까요

**Comment by youngrongoh** [comment]
앗 다르게 되어있네요..!😱

프론트는 386으로 시작하고
백은 957로 시작하는데

![클라이언트id](https://user-images.githubusercontent.com/64844815/116953049-373ac580-acc7-11eb-82c2-45957061cda2.png)
이거 사용하는거 아닌가요??

**Comment by youngrongoh** [comment]
클라이언트 아이디를 똑같이 맞추니 잘 동작하네요!ㅎㅎ
![응답객체](https://user-images.githubusercontent.com/64844815/116953346-f2fbf500-acc7-11eb-9e3c-08d5aafa33b0.png)

**Comment by castleMo** [comment]
386이 맞습니다!
제가 수정을 안했나보네요ㅠㅠ back config 수정해서 올리겠습니다.

**Comment by castleMo** [comment]
구글 드라이브에 v2올렸습니다!
- 수정사항: GOOGLE_CLIENT_ID
