### ISSUE TITLE
사용자가 대표 태그를 어떻게 설정하도록 할까요?

### ISSUE THREAD

**Issue by youngrongoh** [LM-channel-team-project/WantoDo#144]
태스크마다 대표 태그를 설정할 수 있는데,

사용자가 대표 태그를 어떻게 설정하도록 할까요?

어디서? 어떻게?

태스크 수정 모달에서 태그를 클릭하면 대표태그가 되도록?

**Comment by hae-on** [comment]
태그가 있는 곳마다 태그를 꾸욱 누르거나 클릭?에 따라 대표태그가 되도록 하는 건 어떤가요???

**Comment by youngrongoh** [comment]
> 태그가 있는 곳마다 태그를 꾸욱 누르거나 클릭?에 따라 대표태그가 되도록 하는 건 어떤가요???

꾸욱 1초 동안 누르고 있으면 대표태그 되도록..!
한 번 해볼게요 ㅎㅎ
