### ISSUE TITLE
[backend] src/middlewares/google.ts 1번째 줄 

### ISSUE THREAD

**Issue by hyunbin1** [LM-channel-team-project/WantoDo#15]
[backend] src/middlewares/google.ts 1번째 줄 ` import GoogleAuthLibrary, { OAuth2Client } from 'google-auth-library';`
작동 오류

**Comment by castleMo** [comment]
혹시 어떤 버그일까요?
code pull 받고 npm install 해주셨을까요?

**Comment by hyunbin1** [comment]
아 버그까지는 아닌것 같은데 항목이 이거밖에 없길레..! 아 npm install 했는데 from 뒤에 google-auth-library가 실행이 안되는거 같습니다! 혹시 npm 설치가 덜되서 그런건가요?

**Comment by castleMo** [comment]
config파일 src 밑에 넣고 npm install하셨는대 똑같은발생나오시면 연락주세요

**Comment by hyunbin1** [comment]
작동 순조로움
