### ISSUE TITLE
[🐛 버그] profile 수정 요청에 대한 에러

### ISSUE THREAD

**Issue by youngrongoh** [LM-channel-team-project/WantoDo#179]
## 🐛 Bug report

|프론트 에러| 서버 에러|
|:-:|:-:|
|![프론트 에러](https://user-images.githubusercontent.com/64844815/117773675-907c9900-b273-11eb-97a7-7f8aa101a833.png)|![백엔드 에러](https://user-images.githubusercontent.com/64844815/117773485-51e6de80-b273-11eb-88e6-b0ff47b28b78.png)
|

요청 헤더에 `Access-Control-Allow-Origin: *`를 추가해도 해결 안됨

## 예상된 기능 혹은 화면
변경된 프로필을 서버에 전송하여 프로필 업데이트

## 재연할 수 있는 방법

프론트에서 백으로 PATCH 요청 보내면 CORS 에러 발생

**Comment by castleMo** [comment]
cors 처리완료
