### ISSUE TITLE
백엔드 문서 task의 period 객체 속성 타입 질문

### ISSUE THREAD

**Issue by youngrongoh** [LM-channel-team-project/WantoDo#181]
![period 객체](https://user-images.githubusercontent.com/64844815/117790056-efe2a500-b283-11eb-81db-28d978460a74.png)

성모님~
start, end 는 타임스템프(넘버) 타입인가요? 객체인가요?

![프론트 에러](https://user-images.githubusercontent.com/64844815/117790800-a8a8e400-b284-11eb-9d1a-44ab16ebcde2.png)
![백 에러](https://user-images.githubusercontent.com/64844815/117792458-4224c580-b286-11eb-803b-f74a0778438d.png)

![요청 바디](https://user-images.githubusercontent.com/64844815/117791693-8c597700-b285-11eb-8dc3-6e8e4278fa96.png)

타입 때문에 생기는 에러인 것 같기도 하구..ㅠㅠ

**Comment by youngrongoh** [comment]
에러는 왜 생기는지 모르겠네유ㅠㅠ

**Comment by castleMo** [comment]
Docs 수정완료
