### ISSUE TITLE
로그인 페이지 보는 방법

### ISSUE THREAD

**Issue by hae-on** [LM-channel-team-project/WantoDo#184]
# 📚Todo

로그인 페이지 (이름, 좌우명 입력하는 가입창) 수정 중인데요... 로그인 없이 그 창 볼 수 없나요?? 계속 새 아이디 파서 하고 있는데 새로고침하면 자동가입 돼더라구요...ㅠㅠㅠ http://localhost:3000/login으로 적으면 첫 화면만 나오네요 ㅠ

**Comment by youngrongoh** [comment]
지금 탈퇴기능을 안 만들어서 그래요 ㅠㅠ
한 번 가입된 상태로 접근이 안 되실거에요
스토리북에서 볼 수 있도록 만드는 중이에요 곧 pr올리겠습니다!

**Comment by hae-on** [comment]
감사합니다~~~😄
