### ISSUE TITLE
[🐛 버그] 테스크에 날짜 지정하지 않으면 조회할 수 없는 이슈

### ISSUE THREAD

**Issue by youngrongoh** [LM-channel-team-project/WantoDo#212]
## 🐛 Bug report

날짜를 지정하지 않은 테스크의 경우 등록은 가능하지만
조회할 때 월 단위로 서버에 요청하므로 날짜 데이터가 없는 테스크 조회 불가

## 예상된 기능 혹은 화면
날짜를 지정하지 않은 테스크는 항상 조회 해올거라 생각했음

## 재연할 수 있는 방법

퀵폼에서 테스크 등록 후 새로고침하면 조회 안됨

**Comment by castleMo** [comment]
날짜를 지정하지 않은 Task는 시작 종료시간을 생성시간과 동일하게 만들어주는게 어떨까요?

**Comment by youngrongoh** [comment]
네 ㅎㅎ 반영해서 pr 올리겠습니다~
