### ISSUE TITLE
[🐛 버그] task 수정 요청 시, checked 상태를 업데이트 할 수 없는 문제

### ISSUE THREAD

**Issue by youngrongoh** [LM-channel-team-project/WantoDo#214]
## 🐛 Bug report

![네트워크 오류](https://user-images.githubusercontent.com/64844815/118587620-e7d0bb00-b7d7-11eb-9332-bf91a9ddb9ca.png)

체크 상태가 프론트에서만 반영되고 서버에 등록되지 않음
테스크 수정 api에서 요구하는 body 정보에 checked 필드가 없음
![수정 api 필드](https://user-images.githubusercontent.com/64844815/118587745-13ec3c00-b7d8-11eb-90b4-6067bdea3420.png)

## 예상된 기능 혹은 화면
check 버튼 클릭하면 checked 상태가 바뀌고 새로고침 해도 변경 내용이 반영 되어야 함

## 재연할 수 있는 방법

태스크에 있는 체크버튼 클릭

**Comment by castleMo** [comment]
확인했습니다.

**Comment by castleMo** [comment]
#192
