### ISSUE TITLE
[🐛 버그] react-router-dom 에러

### ISSUE THREAD

**Issue by hae-on** [LM-channel-team-project/WantoDo#246]
## 🐛 Bug report

<img width="1090" alt="스크린샷 2021-05-24 오전 10 37 27" src="https://user-images.githubusercontent.com/80464961/119285066-2c4ad380-bc7c-11eb-95ad-1f2ad38dee73.png">
<img width="643" alt="스크린샷 2021-05-24 오전 10 38 57" src="https://user-images.githubusercontent.com/80464961/119285100-42f12a80-bc7c-11eb-9483-9093ae211a79.png">

react-router-dom이 설치되지 않습니다 ㅠㅠㅠ yarn install은 정상적으로 했는데 npm i를 하면 저렇게 오류가 뜹니다.
구글링 해보니  react-router-dom 바로 설치하는 명령어 있어서 적어봤는데 npm i 처럼 에러가 뜹니다.
현빈님도 똑같이 에러가 뜨네요 ㅠㅠㅠ

**Comment by youngrongoh** [comment]
`react-router-dom` 패키지는 [로그아웃 기능 추가](https://github.com/LM-channel-team-project/WantoDo/pull/243)하면서 삭제 했습니다..!

`package.json` 파일이 최신으로 유지 되어 있는지 확인 부탁드려요!
`pakage.json` 안에  `react-router-dom` 혹은 `storybook-react-router`이 남아있으면 안 됩니다😊
