### ISSUE TITLE
[Add]: 프로필 css 스타일링

### ISSUE THREAD

**Issue by hae-on** [LM-channel-team-project/WantoDo#35]
프로필 css 스타일링

**Comment by youngrongoh** [comment]
![image](https://user-images.githubusercontent.com/64844815/115027104-3f8cb580-9efe-11eb-9efb-4c60b2193efc.png)
Projects 설정하시면 따로 프로젝트 가서 등록하시지 않아도 더 편하게 관리하실 수 있다는 사실..!🤩

**Comment by hae-on** [comment]
지금 프로필이미지 건드려보고 있는데요! 
<img width="175" alt="스크린샷 2021-04-17 오후 2 10 11" src="https://user-images.githubusercontent.com/80464961/115102623-051b2b00-9f87-11eb-923f-03e1a05df96e.png">
요거 버튼속성때문에 이렇게 나오더라구요 🙀 
버튼 속성에서 손을 대야 할 것 같은데 어떻게 해야할 지 모르겠어서 도움을 청합니다! 
이 아이만 따로 선택해서 버튼 속성을 바꿀 수 있을까요...???
개발자도구로 보니 .button에 한번에 묶인 거 같아서요 ㅠㅠㅠ

**Comment by hyunbin1** [comment]
저 퍼런 네모박스 없이 회색 동그란 부분쪽만 보이고 싶으신건가요?

**Comment by hae-on** [comment]
넵넵 맞습니다! 테두리처럼 둥근 모양으로 있어도 괜찮을 거 같아요!
