### ISSUE TITLE
질문이 있습니다!

### ISSUE THREAD

**Issue by hae-on** [LM-channel-team-project/WantoDo#57]
<질문 1>
어제 다른 파일에서 npm install을 했습니다.
근데 wantodo package-lock.json에도 변경사항이 생긴 것 같더라구요.

<img width="799" alt="스크린샷 2021-04-22 오후 6 10 53" src="https://user-images.githubusercontent.com/80464961/115688768-67fd2f80-a396-11eb-857f-b0eb37968a34.png">
소스트리 캡쳐 화면입니다.
어떻게 해결해야 할까요.....?? 만약 커밋한다면 브런치 새로 따서 해야하나요???

<질문2>
백준 알고리즘 풀고 있는데 vscode로 출력하고 싶다면 어떻게 해야하나요?
일반적인 문제는 잘 나오는데 (강아지 고양이 문제 같은거...)
<img width="483" alt="스크린샷 2021-04-22 오후 6 15 35" src="https://user-images.githubusercontent.com/80464961/115689129-c0ccc800-a396-11eb-8191-4ed47e48cce9.png">
이거는 출력하면 nan으로 나오더라구요.
<img width="235" alt="스크린샷 2021-04-22 오후 6 19 12" src="https://user-images.githubusercontent.com/80464961/115689656-42bcf100-a397-11eb-9b8b-1a15d18f67b9.png">
이게 a와 b의 값을 vscode에서 따로 숫자로 정의 안해서 숫자가 아니라고 나오는 건가유...???
임의로 숫자값을 줘서 터미널에서 볼 수 있는 방법이 있다면 알려주시면 감사하겠습니다~!

<질문3>
오늘 낮부터 front src에 있는 파일을 실행할 때마다 
<img width="1034" alt="스크린샷 2021-04-22 오후 6 30 17" src="https://user-images.githubusercontent.com/80464961/115691422-012d4580-a399-11eb-8d10-6bf66e674145.png">
이렇게 뜹니다. 얘는 또 왜 이러는걸까요 ㅎㅎㅎ... 😂

<질문4>
질문 여기에 작성하는 거 맞나요...?😅 아니면 바로 삭제하겠습니다~~

구글링 하다가 도저히 답이 안나와서 남겨봅니다..... ㅠㅠㅠ
알려주시면 정말 감사하겠습니다! 🤝🤝🤝

**Comment by youngrongoh** [comment]
아이고 ㅠㅠ 지금 확인했네요..!

**Comment by hae-on** [comment]
도와주셔서 감사합니다~~~ 해결 완료!! 👏
